import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Badge from "../../components/ui/badge/Badge";
import { Modal } from "../../components/ui/modal";
import timeSlotService, {
  TimeSlotDTO,
  TimeSlotStatus,
  BlockReason,
  BlockSlotRequestDTO,
  UpdateSlotDTO,
} from "../../services/timeSlotService";

// =========== HELPERS ===========
const statusBadgeColor = (
  s: string
): "success" | "error" | "dark" | "info" | "warning" | "light" => {
  const map: Record<
    string,
    "success" | "error" | "dark" | "info" | "warning"
  > = {
    AVAILABLE: "success",
    BOOKED: "error",
    BLOCKED: "dark",
    COMPLETED: "info",
    RESERVED: "warning",
  };
  return map[s] || "light";
};

const statusIcon = (s: string) => {
  switch (s) {
    case "AVAILABLE":
      return (
        <svg
          className="h-5 w-5 text-green-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
          />
        </svg>
      );
    case "BOOKED":
      return (
        <svg
          className="h-5 w-5 text-red-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
          />
        </svg>
      );
    case "BLOCKED":
      return (
        <svg
          className="h-5 w-5 text-gray-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"
          />
        </svg>
      );
    case "COMPLETED":
      return (
        <svg
          className="h-5 w-5 text-blue-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M5 13l4 4L19 7"
          />
        </svg>
      );
    default:
      return null;
  }
};

const sourceLabel = (s?: string) => {
  switch (s) {
    case "MANUAL":
      return "Manually created";
    case "BULK":
      return "Bulk generated";
    case "TEMPLATE":
      return "Generated by template";
    default:
      return s || "Unknown";
  }
};

const sourceIcon = (s?: string) => {
  switch (s) {
    case "MANUAL":
      return (
        <svg
          className="h-4 w-4 text-brand-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
          />
        </svg>
      );
    case "BULK":
      return (
        <svg
          className="h-4 w-4 text-orange-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
          />
        </svg>
      );
    case "TEMPLATE":
      return (
        <svg
          className="h-4 w-4 text-purple-500"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"
          />
        </svg>
      );
    default:
      return null;
  }
};

const fmt = (t: string) => (t ? t.substring(0, 5) : "-");
const fmtDate = (d: string) => {
  if (!d) return "-";
  return new Date(d + "T00:00:00").toLocaleDateString("vi-VN", {
    weekday: "long",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
};
const fmtDateTime = (dt?: string) => {
  if (!dt) return "-";
  const d = new Date(dt);
  return d.toLocaleString("vi-VN", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

// =========== PROPS ===========
interface SlotDetailDrawerProps {
  isOpen: boolean;
  slot: TimeSlotDTO | null;
  onClose: () => void;
  onRefresh: () => void;
}

// =========== COMPONENT ===========
export default function SlotDetailDrawer({
  isOpen,
  slot,
  onClose,
  onRefresh,
}: SlotDetailDrawerProps) {
  const navigate = useNavigate();

  // Block modal
  const [blockModalOpen, setBlockModalOpen] = useState(false);
  const [blockReason, setBlockReason] = useState(BlockReason.OTHER as string);
  const [blockNote, setBlockNote] = useState("");
  const [blockSaving, setBlockSaving] = useState(false);

  // Edit modal
  const [editModalOpen, setEditModalOpen] = useState(false);
  const [editForm, setEditForm] = useState<UpdateSlotDTO>({
    startTime: "",
    endTime: "",
  });
  const [editSaving, setEditSaving] = useState(false);

  // Edit block reason modal (for BLOCKED slots)
  const [editBlockModalOpen, setEditBlockModalOpen] = useState(false);
  const [editBlockReason, setEditBlockReason] = useState(
    BlockReason.OTHER as string
  );
  const [editBlockNote, setEditBlockNote] = useState("");
  const [editBlockSaving, setEditBlockSaving] = useState(false);

  // Action loading states
  const [actionLoading, setActionLoading] = useState(false);

  if (!isOpen || !slot) return null;

  // =========== ACTIONS ===========
  const handleBlock = async () => {
    setBlockSaving(true);
    try {
      const data: BlockSlotRequestDTO = {
        reason: blockReason,
        note: blockNote || undefined,
      };
      await timeSlotService.blockTimeSlot(slot.id, data);
      setBlockModalOpen(false);
      setBlockNote("");
      setBlockReason(BlockReason.OTHER);
      onClose();
      onRefresh();
    } catch (e) {
      console.error("Block failed:", e);
      alert("Failed to block slot. Please try again.");
    } finally {
      setBlockSaving(false);
    }
  };

  const handleUnblock = async () => {
    if (!confirm("Are you sure you want to unblock this slot?")) return;
    setActionLoading(true);
    try {
      await timeSlotService.unblockTimeSlot(slot.id);
      onClose();
      onRefresh();
    } catch (e) {
      console.error("Unblock failed:", e);
      alert("Failed to unblock slot. Please try again.");
    } finally {
      setActionLoading(false);
    }
  };

  const handleDelete = async () => {
    if (
      !confirm(
        "Are you sure you want to delete this slot? This action cannot be undone."
      )
    )
      return;
    setActionLoading(true);
    try {
      await timeSlotService.deleteTimeSlot(slot.id);
      onClose();
      onRefresh();
    } catch (e) {
      console.error("Delete failed:", e);
      alert("Failed to delete slot. Please try again.");
    } finally {
      setActionLoading(false);
    }
  };

  const handleEdit = async () => {
    setEditSaving(true);
    try {
      await timeSlotService.updateTimeSlot(slot.id, editForm);
      setEditModalOpen(false);
      onClose();
      onRefresh();
    } catch (e) {
      console.error("Update failed:", e);
      alert("Failed to update slot. Please try again.");
    } finally {
      setEditSaving(false);
    }
  };

  const handleEditBlockReason = async () => {
    setEditBlockSaving(true);
    try {
      // Unblock then re-block with new reason
      await timeSlotService.unblockTimeSlot(slot.id);
      await timeSlotService.blockTimeSlot(slot.id, {
        reason: editBlockReason,
        note: editBlockNote || undefined,
      });
      setEditBlockModalOpen(false);
      onClose();
      onRefresh();
    } catch (e) {
      console.error("Edit block reason failed:", e);
      alert("Failed to update block reason. Please try again.");
    } finally {
      setEditBlockSaving(false);
    }
  };

  const openEditModal = () => {
    setEditForm({
      startTime: slot.startTime,
      endTime: slot.endTime,
      note: slot.note,
    });
    setEditModalOpen(true);
  };

  const openBlockModal = () => {
    setBlockReason(BlockReason.OTHER);
    setBlockNote("");
    setBlockModalOpen(true);
  };

  const openEditBlockModal = () => {
    setEditBlockReason(slot.blockReason || BlockReason.OTHER);
    setEditBlockNote(slot.blockNote || "");
    setEditBlockModalOpen(true);
  };

  // =========== RENDER ===========
  return (
    <>
      {/* Drawer overlay + panel */}
      <div className="fixed inset-0 z-[99999] flex">
        {/* Backdrop */}
        <div
          className="flex-1 bg-black/30 backdrop-blur-sm transition-opacity"
          onClick={onClose}
        />
        {/* Drawer panel */}
        <div className="flex w-full max-w-md flex-col bg-white shadow-2xl dark:bg-gray-900">
          {/* ── Header ── */}
          <div className="flex items-center justify-between border-b border-gray-200 px-6 py-4 dark:border-gray-700">
            <div className="flex items-center gap-3">
              {statusIcon(slot.status)}
              <div>
                <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
                  Slot #{slot.id}
                </h3>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Time Slot Detail
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="rounded-lg p-2 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600 dark:hover:bg-gray-800 dark:hover:text-white"
            >
              <svg
                className="h-5 w-5"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>

          {/* ── Body (scrollable) ── */}
          <div className="flex-1 overflow-y-auto px-6 py-5">
            <div className="space-y-6">
              {/* ── Section: Status & Source ── */}
              <div className="flex items-center gap-2">
                <Badge
                  variant="solid"
                  color={statusBadgeColor(slot.status)}
                >
                  {slot.status}
                </Badge>
                {slot.source && (
                  <Badge variant="light" size="sm" color="light">
                    {slot.source}
                  </Badge>
                )}
              </div>

              {/* ── Section: Doctor ── */}
              <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700">
                <div className="mb-2 flex items-center gap-2">
                  <svg
                    className="h-4 w-4 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                    />
                  </svg>
                  <span className="text-xs font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                    Doctor
                  </span>
                </div>
                <p className="text-sm font-semibold text-gray-900 dark:text-white">
                  {slot.doctorName}
                </p>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  {slot.specialization || "General"}
                </p>
              </div>

              {/* ── Section: Date & Time ── */}
              <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700">
                <div className="mb-3 flex items-center gap-2">
                  <svg
                    className="h-4 w-4 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <span className="text-xs font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                    Schedule
                  </span>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-xs font-medium text-gray-500 dark:text-gray-400">
                      Date
                    </p>
                    <p className="mt-0.5 text-sm font-medium text-gray-900 dark:text-white">
                      {fmtDate(slot.slotDate)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs font-medium text-gray-500 dark:text-gray-400">
                      Time
                    </p>
                    <p className="mt-0.5 text-sm font-medium text-gray-900 dark:text-white">
                      {fmt(slot.startTime)} – {fmt(slot.endTime)}
                    </p>
                  </div>
                </div>
              </div>

              {/* ── Section: Appointment (only if booked) ── */}
              {(slot.status === TimeSlotStatus.BOOKED ||
                slot.appointmentCode) && (
                <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-900/20">
                  <div className="mb-3 flex items-center gap-2">
                    <svg
                      className="h-4 w-4 text-blue-500"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
                      />
                    </svg>
                    <span className="text-xs font-semibold uppercase tracking-wider text-blue-600 dark:text-blue-400">
                      Appointment
                    </span>
                  </div>
                  <div className="space-y-2">
                    <div>
                      <p className="text-xs font-medium text-blue-600 dark:text-blue-400">
                        Appointment Code
                      </p>
                      <p className="text-sm font-bold text-blue-800 dark:text-blue-300">
                        {slot.appointmentCode || "N/A"}
                      </p>
                    </div>
                    {slot.appointmentId && (
                      <div>
                        <p className="text-xs font-medium text-blue-600 dark:text-blue-400">
                          Appointment ID
                        </p>
                        <p className="text-sm text-blue-700 dark:text-blue-300">
                          #{slot.appointmentId}
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* ── Section: Block Info (only if blocked) ── */}
              {slot.status === TimeSlotStatus.BLOCKED && (
                <div className="rounded-xl border border-red-200 bg-red-50 p-4 dark:border-red-800 dark:bg-red-900/20">
                  <div className="mb-3 flex items-center gap-2">
                    <svg
                      className="h-4 w-4 text-red-500"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
                      />
                    </svg>
                    <span className="text-xs font-semibold uppercase tracking-wider text-red-600 dark:text-red-400">
                      Block Information
                    </span>
                  </div>
                  <div className="space-y-2">
                    <div>
                      <p className="text-xs font-medium text-red-600 dark:text-red-400">
                        Reason
                      </p>
                      <p className="text-sm font-semibold text-red-800 dark:text-red-300">
                        {slot.blockReason || "N/A"}
                      </p>
                    </div>
                    {slot.blockNote && (
                      <div>
                        <p className="text-xs font-medium text-red-600 dark:text-red-400">
                          Note
                        </p>
                        <p className="text-sm text-red-700 dark:text-red-300">
                          {slot.blockNote}
                        </p>
                      </div>
                    )}
                    {slot.blockedByName && (
                      <div>
                        <p className="text-xs font-medium text-red-600 dark:text-red-400">
                          Blocked By
                        </p>
                        <p className="text-sm text-red-700 dark:text-red-300">
                          {slot.blockedByName}
                        </p>
                      </div>
                    )}
                    {slot.blockedAt && (
                      <div>
                        <p className="text-xs font-medium text-red-600 dark:text-red-400">
                          Blocked At
                        </p>
                        <p className="text-sm text-red-700 dark:text-red-300">
                          {fmtDateTime(slot.blockedAt)}
                        </p>
                      </div>
                    )}
                    {slot.blockUntil && (
                      <div>
                        <p className="text-xs font-medium text-red-600 dark:text-red-400">
                          Block Until
                        </p>
                        <p className="text-sm text-red-700 dark:text-red-300">
                          {fmtDateTime(slot.blockUntil)}
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* ── Section: Source ── */}
              <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700">
                <div className="mb-3 flex items-center gap-2">
                  <svg
                    className="h-4 w-4 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <span className="text-xs font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                    Source
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  {sourceIcon(slot.source)}
                  <p className="text-sm text-gray-700 dark:text-gray-300">
                    {sourceLabel(slot.source)}
                  </p>
                </div>
                {slot.batchId && (
                  <div className="mt-2">
                    <p className="text-xs font-medium text-gray-500 dark:text-gray-400">
                      Batch ID
                    </p>
                    <p className="mt-0.5 truncate font-mono text-xs text-gray-600 dark:text-gray-400">
                      {slot.batchId}
                    </p>
                  </div>
                )}
              </div>

              {/* ── Section: Note ── */}
              {slot.note && (
                <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700">
                  <div className="mb-2 flex items-center gap-2">
                    <svg
                      className="h-4 w-4 text-gray-400"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z"
                      />
                    </svg>
                    <span className="text-xs font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                      Note
                    </span>
                  </div>
                  <p className="text-sm text-gray-700 dark:text-gray-300">
                    {slot.note}
                  </p>
                </div>
              )}

              {/* ── Section: Audit ── */}
              <div className="rounded-xl border border-gray-200 p-4 dark:border-gray-700">
                <div className="mb-3 flex items-center gap-2">
                  <svg
                    className="h-4 w-4 text-gray-400"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                    />
                  </svg>
                  <span className="text-xs font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500">
                    Audit
                  </span>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <p className="text-xs font-medium text-gray-500 dark:text-gray-400">
                      Created At
                    </p>
                    <p className="mt-0.5 text-xs text-gray-700 dark:text-gray-300">
                      {fmtDateTime(slot.createdAt)}
                    </p>
                  </div>
                  <div>
                    <p className="text-xs font-medium text-gray-500 dark:text-gray-400">
                      Updated At
                    </p>
                    <p className="mt-0.5 text-xs text-gray-700 dark:text-gray-300">
                      {fmtDateTime(slot.updatedAt)}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* ── Footer: Actions ── */}
          <div className="border-t border-gray-200 px-6 py-4 dark:border-gray-700">
            {/* AVAILABLE actions */}
            {slot.status === TimeSlotStatus.AVAILABLE && (
              <div className="flex flex-col gap-2">
                <button
                  onClick={openEditModal}
                  disabled={actionLoading}
                  className="flex w-full items-center justify-center gap-2 rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-brand-600 disabled:opacity-50"
                >
                  <svg
                    className="h-4 w-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                    />
                  </svg>
                  Edit Time
                </button>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={openBlockModal}
                    disabled={actionLoading}
                    className="flex items-center justify-center gap-2 rounded-lg bg-gray-800 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-gray-700 disabled:opacity-50 dark:bg-gray-700 dark:hover:bg-gray-600"
                  >
                    <svg
                      className="h-4 w-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"
                      />
                    </svg>
                    Block
                  </button>
                  <button
                    onClick={handleDelete}
                    disabled={actionLoading}
                    className="flex items-center justify-center gap-2 rounded-lg border border-red-300 px-4 py-2.5 text-sm font-medium text-red-600 transition-colors hover:bg-red-50 disabled:opacity-50 dark:border-red-700 dark:text-red-400 dark:hover:bg-red-900/20"
                  >
                    <svg
                      className="h-4 w-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                      />
                    </svg>
                    Delete
                  </button>
                </div>
              </div>
            )}

            {/* BOOKED actions */}
            {slot.status === TimeSlotStatus.BOOKED && (
              <div className="space-y-3">
                <div className="flex items-center gap-2 rounded-lg bg-yellow-50 p-3 dark:bg-yellow-900/20">
                  <svg
                    className="h-5 w-5 shrink-0 text-yellow-500"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4.5c-.77-.833-2.694-.833-3.464 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z"
                    />
                  </svg>
                  <p className="text-sm text-yellow-700 dark:text-yellow-400">
                    This slot has an active appointment. Direct modifications
                    are not allowed.
                  </p>
                </div>
                {slot.appointmentId && (
                  <button
                    className="flex w-full items-center justify-center gap-2 rounded-lg border border-blue-300 px-4 py-2.5 text-sm font-medium text-blue-600 transition-colors hover:bg-blue-50 dark:border-blue-700 dark:text-blue-400 dark:hover:bg-blue-900/20"
                    onClick={() => {
                      onClose();
                      navigate(`/admin/appointment-detail/${slot.appointmentId}`);
                    }}
                  >
                    <svg
                      className="h-4 w-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                      />
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
                      />
                    </svg>
                    View Appointment
                  </button>
                )}
                <p className="text-center text-xs text-gray-500 dark:text-gray-400">
                  To cancel this appointment, please use the Appointment
                  Management page.
                </p>
              </div>
            )}

            {/* BLOCKED actions */}
            {slot.status === TimeSlotStatus.BLOCKED && (
              <div className="flex flex-col gap-2">
                <button
                  onClick={handleUnblock}
                  disabled={actionLoading}
                  className="flex w-full items-center justify-center gap-2 rounded-lg bg-green-600 px-4 py-2.5 text-sm font-medium text-white transition-colors hover:bg-green-500 disabled:opacity-50"
                >
                  <svg
                    className="h-4 w-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z"
                    />
                  </svg>
                  Unblock Slot
                </button>
                <button
                  onClick={openEditBlockModal}
                  disabled={actionLoading}
                  className="flex w-full items-center justify-center gap-2 rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-50 disabled:opacity-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-800"
                >
                  <svg
                    className="h-4 w-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                    />
                  </svg>
                  Edit Block Reason
                </button>
              </div>
            )}

            {/* COMPLETED - read only */}
            {slot.status === TimeSlotStatus.COMPLETED && (
              <div className="flex items-center gap-2 rounded-lg bg-blue-50 p-3 dark:bg-blue-900/20">
                <svg
                  className="h-5 w-5 shrink-0 text-blue-500"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
                <p className="text-sm text-blue-700 dark:text-blue-400">
                  This slot is completed. No further actions available.
                </p>
              </div>
            )}

            {/* RESERVED - read only */}
            {slot.status === TimeSlotStatus.RESERVED && (
              <div className="flex items-center gap-2 rounded-lg bg-amber-50 p-3 dark:bg-amber-900/20">
                <svg
                  className="h-5 w-5 shrink-0 text-amber-500"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
                <p className="text-sm text-amber-700 dark:text-amber-400">
                  This slot is reserved. Waiting for confirmation.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* =========== BLOCK MODAL =========== */}
      <Modal
        isOpen={blockModalOpen}
        onClose={() => setBlockModalOpen(false)}
        className="max-w-md p-6"
      >
        <h3 className="mb-4 text-lg font-semibold text-gray-900 dark:text-white">
          Block Time Slot
        </h3>
        <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">
          Block slot #{slot.id} ({fmt(slot.startTime)} – {fmt(slot.endTime)} on{" "}
          {fmtDate(slot.slotDate)})
        </p>
        <div className="space-y-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Reason <span className="text-red-500">*</span>
            </label>
            <select
              value={blockReason}
              onChange={(e) => setBlockReason(e.target.value)}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            >
              {Object.values(BlockReason).map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Note
            </label>
            <textarea
              value={blockNote}
              onChange={(e) => setBlockNote(e.target.value)}
              rows={3}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
              placeholder="Optional note..."
            />
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => setBlockModalOpen(false)}
              className="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-sm dark:border-gray-600 dark:text-gray-300"
            >
              Cancel
            </button>
            <button
              onClick={handleBlock}
              disabled={blockSaving}
              className="flex-1 rounded-lg bg-gray-800 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700 disabled:opacity-50"
            >
              {blockSaving ? "Blocking..." : "Confirm Block"}
            </button>
          </div>
        </div>
      </Modal>

      {/* =========== EDIT MODAL =========== */}
      <Modal
        isOpen={editModalOpen}
        onClose={() => setEditModalOpen(false)}
        className="max-w-md p-6"
      >
        <h3 className="mb-4 text-lg font-semibold text-gray-900 dark:text-white">
          Edit Time Slot
        </h3>
        <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">
          Edit slot #{slot.id} for {slot.doctorName}
        </p>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                Start Time
              </label>
              <input
                type="time"
                value={editForm.startTime}
                onChange={(e) =>
                  setEditForm({ ...editForm, startTime: e.target.value })
                }
                className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
              />
            </div>
            <div>
              <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
                End Time
              </label>
              <input
                type="time"
                value={editForm.endTime}
                onChange={(e) =>
                  setEditForm({ ...editForm, endTime: e.target.value })
                }
                className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
              />
            </div>
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Note
            </label>
            <textarea
              value={editForm.note || ""}
              onChange={(e) =>
                setEditForm({ ...editForm, note: e.target.value })
              }
              rows={2}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
              placeholder="Optional note..."
            />
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => setEditModalOpen(false)}
              className="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-sm dark:border-gray-600 dark:text-gray-300"
            >
              Cancel
            </button>
            <button
              onClick={handleEdit}
              disabled={editSaving}
              className="flex-1 rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white hover:bg-brand-600 disabled:opacity-50"
            >
              {editSaving ? "Saving..." : "Save Changes"}
            </button>
          </div>
        </div>
      </Modal>

      {/* =========== EDIT BLOCK REASON MODAL =========== */}
      <Modal
        isOpen={editBlockModalOpen}
        onClose={() => setEditBlockModalOpen(false)}
        className="max-w-md p-6"
      >
        <h3 className="mb-4 text-lg font-semibold text-gray-900 dark:text-white">
          Edit Block Reason
        </h3>
        <p className="mb-4 text-sm text-gray-500 dark:text-gray-400">
          Update the block reason for slot #{slot.id}
        </p>
        <div className="space-y-4">
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Reason <span className="text-red-500">*</span>
            </label>
            <select
              value={editBlockReason}
              onChange={(e) => setEditBlockReason(e.target.value)}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            >
              {Object.values(BlockReason).map((r) => (
                <option key={r} value={r}>
                  {r}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="mb-1 block text-sm font-medium text-gray-700 dark:text-gray-300">
              Note
            </label>
            <textarea
              value={editBlockNote}
              onChange={(e) => setEditBlockNote(e.target.value)}
              rows={3}
              className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
              placeholder="Optional note..."
            />
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => setEditBlockModalOpen(false)}
              className="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-sm dark:border-gray-600 dark:text-gray-300"
            >
              Cancel
            </button>
            <button
              onClick={handleEditBlockReason}
              disabled={editBlockSaving}
              className="flex-1 rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white hover:bg-brand-600 disabled:opacity-50"
            >
              {editBlockSaving ? "Saving..." : "Update Reason"}
            </button>
          </div>
        </div>
      </Modal>
    </>
  );
}
