package com.q2k.meditech.entity.enums;

public enum ActivityType {
    // Auth
    LOGIN,
    LOGOUT,
    PASSWORD_CHANGE,

    // User Management
    CREATED_USER,
    UPDATED_USER,
    DISABLED_USER,
    ASSIGNED_ROLE,
    RESET_PASSWORD,
    PROFILE_UPDATE,

    // Appointments
    CREATED_APPOINTMENT,
    CONFIRMED_APPOINTMENT,
    CHECKED_IN_PATIENT,
    CANCELLED_APPOINTMENT,
    RESCHEDULED_APPOINTMENT,

    // Schedule & Time Slots
    CREATED_SCHEDULE,
    UPDATED_SCHEDULE,
    DELETED_SCHEDULE,
    ADDED_SCHEDULE_EXCEPTION,
    DELETED_SCHEDULE_EXCEPTION,
    GENERATED_TIME_SLOTS,
    CREATED_TIME_SLOT,
    UPDATED_TIME_SLOT,
    DELETED_TIME_SLOT,
    BLOCKED_TIME_SLOT,
    UNBLOCKED_TIME_SLOT,
    BULK_CREATED_TIME_SLOTS,
    BULK_BLOCKED_TIME_SLOTS,
    BULK_UNBLOCKED_TIME_SLOTS,
    ROLLED_BACK_TIME_SLOTS,

    // Prescriptions
    CREATED_PRESCRIPTION,
    APPLIED_TEMPLATE,

    // Payments
    PROCESSED_PAYMENT,
    ISSUED_REFUND,

    // System
    CHANGED_SETTINGS,
    CREATED_BACKUP,
    ENABLED_MAINTENANCE,

    // Content
    UPDATED_PAGE,
    ADDED_SPECIALIZATION,
    MODIFIED_TEMPLATE
}
