package com.q2k.meditech.entity.enums;

/**
 * Detailed notification sub-type / category
 * Groups into NotificationType:
 *   APPOINTMENT: NEW_BOOKING, APPOINTMENT_CANCELLED, APPOINTMENT_RESCHEDULED, PATIENT_CHECKED_IN, NO_SHOW_MARKED
 *   PAYMENT:     MOMO_PAYMENT_RECEIVED, PAYMENT_FAILED, NEW_PENDING_PAYMENT, OVERDUE_PAYMENT
 *   PATIENT:     NEW_PATIENT_REGISTERED, PATIENT_PROFILE_UPDATED
 *   SYSTEM:      MAINTENANCE_SCHEDULED, BACKUP_COMPLETED, SETTING_CHANGED
 */
public enum NotificationCategory {

    // --- Appointment ---
    NEW_BOOKING,
    /** In-app notice to patient: staff confirmed their appointment */
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    PATIENT_CHECKED_IN,
    NO_SHOW_MARKED,
    DOCTOR_NOTIFIED,

    // --- Payment ---
    MOMO_PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    NEW_PENDING_PAYMENT,
    OVERDUE_PAYMENT,

    // --- Patient ---
    NEW_PATIENT_REGISTERED,
    PATIENT_PROFILE_UPDATED,

    // --- System ---
    MAINTENANCE_SCHEDULED,
    BACKUP_COMPLETED,
    SETTING_CHANGED
}
