package com.q2k.meditech.service;

import com.q2k.meditech.dto.receptionist.*;
import com.q2k.meditech.util.ExportUtil;
import com.q2k.meditech.util.ExportUtil.ExportColumn;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Export service for Receptionist Reports — PDF & Excel.
 * Uses the existing ExportUtil pattern.
 * <p>
 * Rate-limiting: max 10 exports per user per day, tracked in-memory.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ReceptionistReportExportService {

    private final ReceptionistReportService reportService;

    private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("HH:mm:ss");
    private static final DateTimeFormatter DATETIME_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    // In-memory rate limiter: key = "userId:date" → count
    private final Map<String, AtomicInteger> exportCounts = new ConcurrentHashMap<>();
    private static final int MAX_EXPORTS_PER_DAY = 10;

    // ============================================================
    //  6.1  Daily Appointments Report
    // ============================================================

    public byte[] exportDailyAppointmentsCsv(LocalDate date, Long doctorId) {
        DailyAppointmentReportDTO report = reportService.getDailyAppointmentReport(date, doctorId);
        return ExportUtil.toCsv(appointmentColumns(), report.getAppointments());
    }

    public byte[] exportDailyAppointmentsExcel(LocalDate date, Long doctorId) throws IOException {
        DailyAppointmentReportDTO report = reportService.getDailyAppointmentReport(date, doctorId);
        return ExportUtil.toExcel(appointmentColumns(), report.getAppointments(),
                "Daily Appointments " + report.getReportDate());
    }

    public byte[] exportDailyAppointmentsPdf(LocalDate date, Long doctorId) throws IOException {
        DailyAppointmentReportDTO report = reportService.getDailyAppointmentReport(date, doctorId);
        String title = String.format("Daily Appointments Report — %s\n%s | Generated by: %s",
                report.getReportDate(), report.getBranch(), report.getGeneratedBy());
        return ExportUtil.toPdf(appointmentColumns(), report.getAppointments(), title);
    }

    private List<ExportColumn<DailyAppointmentReportDTO.AppointmentRow>> appointmentColumns() {
        return List.of(
                ExportColumn.of("#", row -> ExportUtil.safeToString(row.getQueueNumber())),
                ExportColumn.of("Code", DailyAppointmentReportDTO.AppointmentRow::getAppointmentCode),
                ExportColumn.of("Start Time", row -> row.getStartTime() != null ? row.getStartTime().format(TIME_FMT) : ""),
                ExportColumn.of("End Time", row -> row.getEndTime() != null ? row.getEndTime().format(TIME_FMT) : ""),
                ExportColumn.of("Patient", DailyAppointmentReportDTO.AppointmentRow::getPatientName),
                ExportColumn.of("Phone", DailyAppointmentReportDTO.AppointmentRow::getMaskedPhone),
                ExportColumn.of("Doctor", DailyAppointmentReportDTO.AppointmentRow::getDoctorName),
                ExportColumn.of("Room", DailyAppointmentReportDTO.AppointmentRow::getRoom),
                ExportColumn.of("Status", DailyAppointmentReportDTO.AppointmentRow::getStatus),
                ExportColumn.of("Payment", DailyAppointmentReportDTO.AppointmentRow::getPaymentStatus)
        );
    }

    // ============================================================
    //  6.2  Daily Revenue Summary
    // ============================================================

    public byte[] exportDailyRevenueCsv(LocalDate date) {
        DailyRevenueReportDTO report = reportService.getDailyRevenueReport(date);
        return ExportUtil.toCsv(transactionColumns(), report.getTransactions());
    }

    public byte[] exportDailyRevenueExcel(LocalDate date) throws IOException {
        DailyRevenueReportDTO report = reportService.getDailyRevenueReport(date);
        return ExportUtil.toExcel(transactionColumns(), report.getTransactions(),
                "Daily Revenue " + report.getReportDate());
    }

    public byte[] exportDailyRevenuePdf(LocalDate date) throws IOException {
        DailyRevenueReportDTO report = reportService.getDailyRevenueReport(date);
        String title = String.format("Daily Revenue Summary — %s\nTotal: %s VND | Cash: %s | MoMo: %s\n%s | Generated by: %s",
                report.getReportDate(),
                formatAmount(report.getTotalRevenue()),
                formatAmount(report.getCashTotal()),
                formatAmount(report.getMomoTotal()),
                report.getBranch(),
                report.getGeneratedBy());
        return ExportUtil.toPdf(transactionColumns(), report.getTransactions(), title);
    }

    private List<ExportColumn<DailyRevenueReportDTO.TransactionRow>> transactionColumns() {
        return List.of(
                ExportColumn.of("Code", DailyRevenueReportDTO.TransactionRow::getTransactionCode),
                ExportColumn.of("Paid Time", row -> row.getPaidTime() != null ? row.getPaidTime().format(TIME_FMT) : ""),
                ExportColumn.of("Appointment", DailyRevenueReportDTO.TransactionRow::getAppointmentCode),
                ExportColumn.of("Patient", DailyRevenueReportDTO.TransactionRow::getPatientName),
                ExportColumn.of("Amount (VND)", row -> formatAmount(row.getAmount())),
                ExportColumn.of("Method", DailyRevenueReportDTO.TransactionRow::getPaymentMethod),
                ExportColumn.of("Collected By", DailyRevenueReportDTO.TransactionRow::getCollectedBy)
        );
    }

    // ============================================================
    //  6.3  Queue Performance
    // ============================================================

    public byte[] exportQueuePerformanceCsv() {
        QueuePerformanceReportDTO report = reportService.getQueuePerformanceReport();
        return ExportUtil.toCsv(doctorPerfColumns(), report.getByDoctor());
    }

    public byte[] exportQueuePerformanceExcel() throws IOException {
        QueuePerformanceReportDTO report = reportService.getQueuePerformanceReport();
        return ExportUtil.toExcel(doctorPerfColumns(), report.getByDoctor(),
                "Queue Performance " + report.getReportDate());
    }

    public byte[] exportQueuePerformancePdf() throws IOException {
        QueuePerformanceReportDTO report = reportService.getQueuePerformanceReport();
        String title = String.format(
                "Queue Performance Report — %s\nChecked-In: %d | Avg Wait: %.1f min | No-Show: %d (%.1f%%)\n%s | Generated by: %s",
                report.getReportDate(),
                report.getTotalCheckedIn(),
                report.getAvgWaitMinutes(),
                report.getNoShowCount(),
                report.getNoShowRate(),
                report.getBranch(),
                report.getGeneratedBy());
        return ExportUtil.toPdf(doctorPerfColumns(), report.getByDoctor(), title);
    }

    private List<ExportColumn<QueuePerformanceReportDTO.DoctorPerformance>> doctorPerfColumns() {
        return List.of(
                ExportColumn.of("Doctor", QueuePerformanceReportDTO.DoctorPerformance::getDoctorName),
                ExportColumn.of("Room", QueuePerformanceReportDTO.DoctorPerformance::getRoom),
                ExportColumn.of("Patients Served", row -> String.valueOf(row.getPatientsServed())),
                ExportColumn.of("Patients Waiting", row -> String.valueOf(row.getPatientsWaiting())),
                ExportColumn.of("Avg Wait (min)", row -> String.valueOf(row.getAvgWaitMinutes())),
                ExportColumn.of("Longest Wait (min)", row -> String.valueOf(row.getLongestWaitMinutes())),
                ExportColumn.of("Peak Hour", QueuePerformanceReportDTO.DoctorPerformance::getPeakHour)
        );
    }

    // ============================================================
    //  Rate-limiting helpers
    // ============================================================

    /**
     * Check and increment export count. Returns true if allowed (< MAX_EXPORTS_PER_DAY).
     */
    public boolean checkAndIncrementExportCount(Long userId) {
        String key = userId + ":" + LocalDate.now();
        AtomicInteger count = exportCounts.computeIfAbsent(key, k -> new AtomicInteger(0));
        int current = count.incrementAndGet();
        if (current > MAX_EXPORTS_PER_DAY) {
            log.warn("User {} exceeded daily export limit ({}/{})", userId, current, MAX_EXPORTS_PER_DAY);
            return false;
        }
        // Cleanup old keys (simple approach — remove entries from previous days)
        cleanupOldEntries();
        return true;
    }

    public int getRemainingExports(Long userId) {
        String key = userId + ":" + LocalDate.now();
        AtomicInteger count = exportCounts.get(key);
        int used = count != null ? count.get() : 0;
        return Math.max(0, MAX_EXPORTS_PER_DAY - used);
    }

    private void cleanupOldEntries() {
        String todaySuffix = ":" + LocalDate.now();
        exportCounts.keySet().removeIf(key -> !key.endsWith(todaySuffix));
    }

    private String formatAmount(BigDecimal amount) {
        if (amount == null) return "0";
        return String.format("%,.0f", amount);
    }
}
